Global:
  Source: "config(local)"
  ChangeMe: "v3"

Log:
  level: "info"
  development: false
  encoding: "console" # console or json
  encoderConfig:
    #  # https://godoc.org/go.uber.org/zap/zapcore#EncoderConfig
    timeKey: "ts"
    nameKey: "apiLogger"
    messageKey: "msg"
    levelKey: "level"
    #  levelEncoder: "lowercase"
    callerKey: "caller"
  #  StacktraceKey: "stacktrace"
  outputPaths:
    - "stdout"
    - "log/API.log"
  #errorOutputPaths:
  #  - "stderr"
  #initialFields:
  #  foo: "bar"

JWT:
  signingKey: "signingKey"

Etcd:
  - Address: "127.0.0.1"
    Port: 2379

Server:
  Name: "TiktokAPIServer"
  Address: "0.0.0.0"
  Port: 8088

Client:
  Echo: true
  Foo: "bar"
  Servers:
    - "127.0.0.1"
    - "192.168.1.1"

MySQL:
  Host: "127.0.0.1"
  Port: 8091
  User: "root"
  Password: "password"
  DBName: "Tiktok"
  CharSet: "utf8mb4"
  ParseTime: true
  loc: "Local"